package GUI;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAL.Cl_Connect;
import DAL.Rank_cl;


/**
 *
 * @author Diep.Tran
 */
public class rankGUI extends JFrame {
	public static DAL.Cl_Connect cl;
	private JPanel start;
	private JLabel rank_user;
    DefaultTableModel tableModel;
    JButton btnFind;
    private JScrollPane jScrollPane1;
    private JTable tblrank;
    
	  
    
    List<Rank_cl> rankList_cl = new ArrayList<>();
    
    /**
     * Creates new form rankFrame
     * @throws IOException 
     * @throws ClassNotFoundException 
     */
    public rankGUI() throws ClassNotFoundException, IOException {
    	 cl = new DAL.Cl_Connect();
        initComponents();
        
        tableModel = (DefaultTableModel) tblrank.getModel();
        
        showrank();
    }
    
    private void showrank() throws ClassNotFoundException, IOException {
    	
        
    	 
    	 rankList_cl= cl.findAll();
    	 Collections.sort(rankList_cl);
        
        tableModel.setRowCount(0);
//        rankList_cl.forEach((rank_cl) -> {
//        	
//            
//           
//        });
        
        rankList_cl.forEach((rank_cl) -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, rank_cl.getUserId(),rank_cl.getUsername(), 
                rank_cl.getPoint(), rank_cl.getN_match(), rank_cl.getWin(),rank_cl.getLose()});
//            if(rank_cl.getUsername().equals("123"))
//            {
//            	System.out.println("rank cua no la "  +tableModel.getRowCount());
//            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws IOException 
     * @throws ClassNotFoundException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws ClassNotFoundException, IOException {
    	ImagePanel background = new ImagePanel("main.png", 0, 0, 800, 600);
    	start=new JPanel();


    	
    	
        btnFind = new JButton("hi");
        JLabel rank_user = new JLabel();
        rank_user.setText(cl.user_rank());
        rank_user.setBounds(50, 50, 50, 50);
        jScrollPane1 = new JScrollPane();
        tblrank = new JTable();
        tblrank.setBounds(0, 0, 200, 200);
//        btnFind.setBounds(0, 0, 50, 50);

        
        tblrank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "ID User","UserName", "Point", "Match", "Win","Lose"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblrank);
        jScrollPane1.setBounds(100, 200, 600, 300);
        start.add(btnFind);
       start.add(rank_user);
        start.add(jScrollPane1);
        
        start.add(background);
        start.setLayout(null);
        
        start.setBounds(0, 0, 800, 600);
        this.add(start);
        
        this.setLayout(null);
		this.setSize(800, 600);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        pack();
    }// </editor-fold>                        

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
//        txtFullname.setText("");
//        cbGender.setSelectedIndex(0);
//        txtAge.setText("");
//        txtEmail.setText("");
//        txtPhoneNumber.setText("");
    }                                        

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, IOException {                                        
        // TODO add your handling code here:
//        String fullname = txtFullname.getText();
//        String gender = cbGender.getSelectedItem().toString();
//        int age = Integer.parseInt(txtAge.getText());
//        String email = txtEmail.getText();
//        String phoneNumber = txtPhoneNumber.getText();
//        
////        rank std = new rank(fullname, gender, email, phoneNumber, age);
////        
////        rankModify.insert(std);
//        
//        showrank();
    }                                       

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
//        int selectedIndex = tblrank.getSelectedRow();
//        if(selectedIndex >= 0) {
//            rank std = rankList.get(selectedIndex);
//            
//            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
//            System.out.println("option : " + option);
//            
//            if(option == 0) {
//                rankModify.delete(std.getId());
//                
//                showrank();
//            }
//        }
    }                                         

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
//        String input = JOptionPane.showInputDialog(this, "Enter full name to search");
//        if(input != null && input.length() > 0) {
//            rankList = rankModify.findByFullname(input);
//            
//            tableModel.setRowCount(0);
//        
//            rankList.forEach((rank) -> {
//                tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, rank.getFullname(), 
//                    rank.getGender(), rank.getEmail(), rank.getPhoneNumber()});
//            });
//        } else {
//            showrank();
//        }
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new rankGUI().setVisible(true);
				} catch (ClassNotFoundException | IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
//    private javax.swing.JButton btnDelete;
////    private javax.swing.JButton btnFind;
//    private javax.swing.JButton btnReset;
//    private javax.swing.JButton btnSave;
//    private javax.swing.JComboBox<String> cbGender;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTable tblrank;
//    private javax.swing.JTextField txtAge;
//    private javax.swing.JTextField txtEmail;
//    private javax.swing.JTextField txtFullname;
//    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration                   
}
